apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-counter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-counter
  template:
    metadata:
      labels:
        app: go-counter
    spec:
      containers:
        - name: counter
          image: coolersai/go-counter-kub-image:latest
          ports:
            - containerPort: 8081